### PR TITLE
SvgTestBox: Added the quick testing application for debugging issues

### PR DESCRIPTION
**Pull request by paulushub**
- Added supporting build libraries (Tests/Libs) for all the framework versions
- SvgTestBox provides text editor viewing, editing and rendering SVG files
- ClipArtViewer is updated to display folder selecting dialog and error notifications.

### CODE REVIEW

**Comment by jogibear9988** [comment]
remove binarys

**Comment by jogibear9988** [comment]
and change gitignore to skip them after the removal

**Comment by paulushub** [comment]
The only binaries are libraries in `Tests/Libs` directory, similar to `SVGImage/Source/SVGImage.Design/libs/`.

**Comment by jogibear9988** [comment]
no, the libs you include are all availble as nugets, the two in design are not

**Comment by jogibear9988** [comment]
you included system.io.dll, system. runtime.dll, ...

**Comment by paulushub** [comment]
Only in the .NET 4.0 folder, which required specialized customization including version redirection to build and included to prevent dependent samples from doing the same customization.
I have spent enough time trying to get these to work, I have other things to do.

**Pull request merged**
