### PR TITLE
Updates to support .NET 8.0

### PR DESCRIPTION
**Pull request by paulushub**
- Updated Readme files.
- Updated Projects files, no code modification required.
- Added a flag to turn off documentation warnings.

### CODE REVIEW

**Comment by paulushub** [comment]
@jogibear9988 I will close this request for now, it seems the AppVeyor build is not yet ready for .NET 8.
Is there a way to set the build target to .NET 8 in the `AppVeyor.yml`?

**Comment by jogibear9988** [comment]
Don‘t know. We could also switch to github actions

**Comment by paulushub** [comment]
We either wait, or since you have the accounts you can implement the switch.

**Comment by jogibear9988** [comment]
You could also do it ;-)
You only need to create the files like here:

https://github.com/dotnetprojects/MonacoRoslynCompletionProvider/tree/main/.github/workflows

or I will do, but don't know when

**Comment by paulushub** [comment]
Creating the workflow will not be a problem. You will still have to handle the AppVeyor part.

**Comment by jogibear9988** [comment]
The AppVeyor is then not needed any more. I'll remove it there

**Comment by jogibear9988** [comment]
and the nuget api key in github actions is store for the whole organization

**Comment by paulushub** [comment]
@jogibear9988 Finally completed the implementation of the GitHub Actions. It took more time than I expected, but was a good leaning process as well.
Most of the tools did not work as expected, and some are simply not flexible. 
Currently, the implementation is as follows:
### Pull Request
The pull request will 
1. Retrieve the current version, based on the currently tagged version
2. Bumped up the version number
3. Update the version information
4. Build (as usual for each supported .NET Framework)
5. Pack (as usual the Nuget packages)

The Pull Request will not release or deploy (as expected), only for testing.

### Push or Merge (to master)
The merging to the master branch will
1. Perform the above steps (in the Pull Request)
2. Deploy to Nuget repository
3. Create a Release on GitHub and add the Nuget packages
4. Build the documentations and deploy it

### Implementations
1. Use `gittools/actions/gitversion` to retrieve the current version
2. Use `roryprimrose/set-vs-sdk-project-version` to update the version
3. Manually, build, pack, and deploy the Nuget packages
4. Use `actions/github-script` to create the GitHub Release, which add the git tag

### Results
The Nuget packages are now more **healthy** than before:
image
***
image

### TODO
Any of these changes will trigger a release, so we may have to wait till there is a need for update.
1. Clean the *.yml (stuff like `Display GitVersion outputs` no longer needed)
2. Change the `GitVersion.yml` (currently set the `next-version = 5.0.118`). With a successfully release, `next-version` is no longer needed.

**Pull request closed without merging**
