### PR TITLE
Refactoring, code improvements and bug fixes

### PR DESCRIPTION
**Pull request by paulushub**
- Moved projects to VS2022 with supports for .NET 6/7
- Updated version information
- Removed the Design project
- Removed the VS2017 project files
- Removed .NETCore 3.0 support
- Removed DotnetProjects namespaces, simplified the namespaces
- Removed the Attribute class, since it is the same as StyleItem class
- Added DocFX projects for building documentations
- Updates to the Nuget package: included Xml-docs, readme etc.
- Fixed null exception in the ViewBoxToSizeNoStretch support when using Drawing sources.

### CODE REVIEW

**Comment by paulushub** [comment]
Do you understand the issue with the deployment?
image

**Comment by jogibear9988** [comment]
jo, i will fix.
Problem is, nuget only can create api keys wich last for a year, after that you need to refresh them

**Comment by paulushub** [comment]
Normally, Nuget will send the notification of expired keys.
Well, can you add the path for the symbol server (.snupkg) too? 
It is actually created but not kept, I think.

BTW, the documentation is active and fully functional. Hope you can find time
to contribute to it - just like you, currently I am really not using C# for paid work 🥲

**Comment by jogibear9988** [comment]
Im using C# at work. But not WPF :-)

Where do I need to add the snupkg? Don't know what you mean.

What do you for work?

**Comment by paulushub** [comment]
> Where do I need to add the snupkg? Don't know what you mean.

```xml
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>	
    
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>portable</DebugType>

  </PropertyGroup>
```

With the `<SymbolPackageFormat>snupkg</SymbolPackageFormat>` the build now outputs 
- DotNetProjects.SVGImage.nupkg
- DotNetProjects.SVGImage.snupkg

But I did not change the artifacts paths
```xml
artifacts:
  - path: '**\DotNetProjects.SVGImage*.nupkg'
```
So, I think only the *.nupkg is picked up.

> What do you for work?

Currently, subcontracting for CI/CD solutions using mainly Python and some C/C++.

**Pull request merged**
