### PR TITLE
Set Override Colors independently for Fill and Stroke

### PR DESCRIPTION
**Pull request by lukas-kirschner**
## Description

Right now, both the fill and stroke colors can be overridden through the `OverrideColor` property in SVGImage. Allowing to override both a fill and a stroke color independently would allow a user to set a stroke color different from a fill color. The two proposed properties, `OverrideFillColor` and `OverrideStrokeColor` are also consistent to the `OverrideStrokeWidth` property that has already been implemented.
Implementing this would also allow users to (partially) work around bug #84 .
By adding two new properties while keeping the current `OverrideColor` property intact, we maintain compatibility and do not introduce any breaking changes.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] .NET Framework, Version 4.0
- [x] .NET Framework, Version 4.5
- [x] .NET Framework, Version 4.6
- [x] .NET Framework, Version 4.7
- [x] .NET Framework, Version 4.8
- [x] .NET Core, Version 3.1
- [x] .NET 6 ~ 8
- [x] All Included Samples

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by lukas-kirschner** [comment]
Hi,
I implemented an example for overriding fill and stroke color separately: Double-Clicking the shape above the black square in the example application now randomly changes the color of stroke and fill, similar to the OverrideColor example at the bottom right.

**Review by jogibear9988 — APPROVED** [review]

**Review by jogibear9988 — APPROVED** [review]

**Comment by tovgroliv** [comment]
https://github.com/dotnetprojects/SVGImage/pull/76

This is an actual clone of my request. But my query requires less overhead due to fewer properties. It's sad that you didn't accept my request. :(

PS I was missing documentation

**Comment by lukas-kirschner** [comment]
> This is an actual clone of my request. But my query requires less overhead due to fewer properties. It's sad that you didn't accept my request. :(

Sorry, I did not see your request since it was closed at the time I opened #85

**Comment by paulushub** [comment]
> It's sad that you didn't accept my request. :(

I needed to work on the project (rework the workflow to use GitHub instead of the AppVeyor), and you were delaying my request for update to your PR, so I closed it and asked you to repost it again whenever you are ready to the **develop** branch.
And, that was the reason why I added the PR check-list and **develop** branch to make work on this project easier, as I am only helping with my limited time.

**Pull request merged**
